#!/usr/bin/env php
<?php

/*    Usage:  ./gpiod start			#for starting or re-starting all pin event-listen and the lazy server
              ./gpiod killall			#for killing all listens and the lazy server
	
      see www.gioexperience.com for more details
*/

$ini=parse_ini_file("/etc/gpiod.ini",true);

$listens=array();
foreach($ini as $section=>$r)
{
	if( $section=="lazy_server" ) continue;
	if( substr($section,0,5)=="event" ) array_push($listens,$section);
}

function fast_request($url)
{
	echo "call $url\n";
	$p=parse_url($url);
	$fp = @fsockopen($p["host"], 80, $errno, $errstr, 1);
	if( $fp==false ) return;
	
	$out = "GET ".$p["path"]."?".$p["query"]." HTTP/1.1\r\n";
    $out .= "Host: ".$p["host"]."\r\n";
    $out .= "Connection: Close\r\n\r\n";
    fwrite($fp, $out);
    fclose($fp);
}

$gpio=trim(exec("whereis gpio | awk '{print $2}'"));
if( $gpio=="" ) die("Error: gpio not found, reinstall\n");

$gpio_btn=trim(exec("whereis gpio_btn | awk '{print $2}'"));
if( $gpio_btn=="" ) die("Error: gpio_btn not found, reinstall\n");

$bin="/usr/local/bin/gpiod";

echo "executable gpio_btn found here: $gpio_btn \n";

// *****************************************************************************************************

if( $argc>1 && $argv[1]=="start_single_listen" )				//for internal use only
{
	//internal usage --->    gpiod start_single_listen $inisection
	//$inisection is the section name in the gpiod.ini

	$key=$argv[2];
	$inisection=$ini[$key];
	$pin=intval(trim($inisection["pin"]));
	$url=trim($inisection["url"]);								//for calling an http api
	$cmd_short=trim($inisection["short"]);						//for exec localy a script or bash command
	$cmd_long=trim($inisection["long"]);						//for exec localy a script or bash command
	
	print_r($inisection);
	
	$url=trim($url,"?&");
	if( strpos($url,"?")===false ) $url.="?1=1";
	
	while(true)
	{
		echo "Wait for pressing pin $pin...\n";
		$cmd="$gpio_btn $pin\n";
		$ret=trim(exec($cmd));
		
		echo "...return $ret\n";
		
		if($ret=="SHORT")
		{
			if( $cmd_short!="" ) 
			{
				echo "Eseguo $cmd_short \n";
				exec("$cmd_short > /dev/null 2>&1 &");
			}
			if( strlen($url)>6 ) fast_request($url."&pin=$pin&key=$key&action=SHORT");
		}
		elseif($ret=="LONG")
		{
			if( $cmd_long!="" ) 
			{
				echo "Eseguo $cmd_long \n";
				exec("$cmd_long > /dev/null 2>&1 &");
			}
			if( strlen($url)>6 ) fast_request($url."&pin=$pin&key=$key&action=LONG");
		}
		else
			continue;
	}
	die();
}
if( $argc>1 && $argv[1]=="lazy" )							//for internal use only
{
	//internal usage --->    gpiod lazy 
	$server=trim($ini["lazy_server"]["server"]);
	$user=trim($ini["lazy_server"]["user"]);
	$password=trim($ini["lazy_server"]["password"]);
	$myself=trim(exec("hostname -I | awk '{print $1}'"));
	
	if( $server=="" ) die("No lazy server\n");
	
	$file_json="/tmp/gpio_lazy.json";
	exec("rm $file_json");
	sleep(1);
	exec("touch $file_json");
	
	$DS18B20s=glob("/sys/bus/w1/devices/28*",GLOB_ONLYDIR );
	//start many process, one for sensors
	foreach($DS18B20s as $DS18B20)
	{
		$DS18B20=basename($DS18B20);
		$pid=pcntl_fork();
		if( $pid==0 )
		{
			echo "Figlio ".getmypid()." per sensore $DS18B20\n";
			while(true)
			{
				$line=exec("cat /sys/bus/w1/devices/$DS18B20/w1_slave | grep \"t=\"");
				$t=substr($line,strpos($line,"t=")+2);
				$t=round($t/1000,1);

				if( !file_exists("/tmp/$DS18B20") ) touch("/tmp/$DS18B20");
				$flock = fopen("/tmp/$DS18B20", 'r');
				flock($flock, LOCK_EX);	
				file_put_contents("/tmp/$DS18B20",$t);
				fclose($flock);
				sleep(5);
			}
		}
	}
	//**************************

	$t0=microtime(true);
	while(true)
	{
		$json=array();
		$t0=microtime(true);
		
		$rs=array();
		exec("$gpio readall",$rs);
		
		for($i=1;$i<=26;$i++)
		{
			if( $i==2 ) 	$json["GPIO$i"]=$rs[4][32];
			elseif( $i==3 ) 	$json["GPIO$i"]=$rs[5][32];
			elseif( $i==4 ) 	$json["GPIO$i"]=$rs[6][32];
			elseif( $i==17 ) 	$json["GPIO$i"]=$rs[8][32];
			elseif( $i==22 ) 	$json["GPIO$i"]=$rs[10][32];
			elseif( $i==10 )	$json["GPIO$i"]=$rs[12][32];
			elseif( $i==9 ) 	$json["GPIO$i"]=$rs[13][32];
			elseif( $i==11 )	$json["GPIO$i"]=$rs[14][32];
			elseif( $i==5 ) 	$json["GPIO$i"]=$rs[17][32];
			elseif( $i==6 ) 	$json["GPIO$i"]=$rs[18][32];
			elseif( $i==13 ) 	$json["GPIO$i"]=$rs[19][32];
			elseif( $i==19 ) 	$json["GPIO$i"]=$rs[20][32];
			elseif( $i==26 ) 	$json["GPIO$i"]=$rs[21][32];

			elseif( $i==14 ) 	$json["GPIO$i"]=$rs[6][47];
			elseif( $i==15 ) 	$json["GPIO$i"]=$rs[7][47];
			elseif( $i==18 ) 	$json["GPIO$i"]=$rs[8][47];
			elseif( $i==23 ) 	$json["GPIO$i"]=$rs[10][47];
			elseif( $i==24 )	$json["GPIO$i"]=$rs[11][47];
			elseif( $i==25 ) 	$json["GPIO$i"]=$rs[13][47];
			elseif( $i==8 ) 	$json["GPIO$i"]=$rs[14][47];
			elseif( $i==7 ) 	$json["GPIO$i"]=$rs[15][47];
			elseif( $i==1 ) 	$json["GPIO$i"]=$rs[16][47];
			elseif( $i==12 ) 	$json["GPIO$i"]=$rs[18][47];
			elseif( $i==16 ) 	$json["GPIO$i"]=$rs[20][47];
			elseif( $i==20 ) 	$json["GPIO$i"]=$rs[21][47];
			elseif( $i==21 )	$json["GPIO$i"]=$rs[22][47];
		}	
		
		echo "T:".(microtime(true)-$t0)."\n";
		foreach($DS18B20s as $DS18B20)
		{
			$DS18B20=basename($DS18B20);
			
			if( !file_exists("/tmp/$DS18B20") ) touch("/tmp/$DS18B20");
			$flock = fopen("/tmp/$DS18B20", 'r');
			flock($flock, LOCK_EX);	
			$json[$DS18B20]=file_get_contents("/tmp/$DS18B20");
			fclose($flock);
		}
		
		$json=json_encode($json,JSON_PRETTY_PRINT);

		if( md5($json)!=md5_file($file_json) )
		{
			echo "cambiato\n";
			file_put_contents($file_json,$json);
			$cmd="sshpass -p{$password} scp $file_json $user@$server:/home/{$user}/{$myself}.json";
			exec($cmd);
		}
		
		usleep(0.1*1000*1000);
	}

	die();
}

elseif( $argc>1 && $argv[1]=="killall" )
{
	//kill all
	echo "Kill all listens\n";
	exec("pkill -f 'gpio_btn'");
	exec("pkill -f 'gpio_btn'");
	exec("pkill -f 'gpiod start_single_listen'");
	exec("pkill -f 'gpiod lazy'");
	exec("pkill -f 'gpio_btn'");
	exec("pkill -f 'gpiod'");
	die();
}

elseif( $argc>1 && $argv[1]=="start" )
{
	exec("pkill -f 'gpiod start_single_listen'");
	sleep(1);
	exec("pkill -f 'gpiod lazy'");
	sleep(1);

	foreach ($listens as $section)
	{
		$cmd="$bin start_single_listen $section ";
		echo "exec] $cmd \n";
		exec("$cmd >/dev/null 2>/dev/null &");
		sleep(2);
	}
	
	echo "Start lazy server....\n";
	$cmd="$bin lazy";
	echo "exec] $cmd \n";
	exec("$cmd >/dev/null 2>/dev/null &");

	echo "All reloaded...\n\n";
}
else
{
	echo "\n";
	echo "Usage:  gpiod start     		#for starting or reload all listens\n";
	echo "        gpiod killall     	#for killing all listens\n";
	echo "\n";
	die();
}


?>
